config/routes.rb
Rails.application.routes.draw do
  resources :boards
  resources :publications 
  devise_for :users
  resources :tags
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "publications#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :publication
  belongs_to :user
end

app/models/publication.rb
class Publication < ApplicationRecord
  validates :name, presence: true

  has_one_attached :foto
  has_many :boards, dependent: :destroy
  has_many :users, through: :boards
  belongs_to :tag
  belongs_to :user

end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :publications
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :publications
  has_many :boards, dependent: :destroy
  has_many :publications, through: :boards
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: %i[ show edit update destroy ]

  # GET /boards or /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1 or /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards or /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to board_url(@board), notice: "Board was successfully created." }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1 or /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to board_url(@board), notice: "Board was successfully updated." }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1 or /boards/1.json
  def destroy
    @board.destroy

    respond_to do |format|
      format.html { redirect_to boards_url, notice: "Board was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def board_params
      params.require(:board).permit(:ToDo, :InProgress, :Done, :publication_id, :user_id)
    end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_publication, only: %i[ show edit update destroy ]

  # GET /publications or /publications.json
  def index
    @publications = Publication.all
   
  end

  # GET /publications/1 or /publications/1.json
  def show
  end

  # GET /publications/new
  def new
    @publication = Publication.new
    @tag = Tag.all
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications or /publications.json
  def create
    @publication = Publication.new(publication_params)

    respond_to do |format|
      if @publication.save
        format.html { redirect_to publication_url(@publication), notice: "Publication was successfully created." }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1 or /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to publication_url(@publication), notice: "Publication was successfully updated." }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1 or /publications/1.json
  def destroy
    @publication.destroy

    respond_to do |format|
      format.html { redirect_to publications_url, notice: "Publication was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publication_params
      params.require(:publication).permit(:name, :content, :tag_id, :user_id, :foto)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: %i[ show edit update destroy ]

  # GET /tags or /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1 or /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags or /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tag_url(@tag), notice: "Tag was successfully created." }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to tag_url(@tag), notice: "Tag was successfully updated." }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url, notice: "Tag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/boards/_board.html.erb
<div id="<%= dom_id board %>">
  <p>
    <strong>Todo:</strong>
    <%= board.ToDo %>
  </p>

  <p>
    <strong>Inprogress:</strong>
    <%= board.InProgress %>
  </p>

  <p>
    <strong>Done:</strong>
    <%= board.Done %>
  </p>

  <p>
    <strong>Publication:</strong>
    <%= board.publication_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= board.user_id %>
  </p>

</div>

app/views/boards/_form.html.erb
<%= form_with(model: board) do |form| %>
  <% if board.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
        <% board.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :ToDo, style: "display: block" %>
    <%= form.text_field :ToDo %>
  </div>

  <div>
    <%= form.label :InProgress, style: "display: block" %>
    <%= form.text_field :InProgress %>
  </div>

  <div>
    <%= form.label :Done, style: "display: block" %>
    <%= form.text_field :Done %>
  </div>

  <div>
    <%= form.label :publication_id, style: "display: block" %>
    <%= form.text_field :publication_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing board</h1>

<%= render "form", board: @board %>

<br>

<div>
  <%= link_to "Show this board", @board %> |
  <%= link_to "Back to boards", boards_path %>
</div>

app/views/boards/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Boards</h1>

<div id="boards">
  <% @boards.each do |board| %>
    <%= render board %>
    <p>
      <%= link_to "Show this board", board %>
    </p>
  <% end %>
</div>

<%= link_to "New board", new_board_path %>

app/views/boards/new.html.erb
<h1>New board</h1>

<%= render "form", board: @board %>

<br>

<div>
  <%= link_to "Back to boards", boards_path %>
</div>

app/views/boards/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @board %>

<div>
  <%= link_to "Edit this board", edit_board_path(@board) %> |
  <%= link_to "Back to boards", boards_path %>

  <%= button_to "Destroy this board", @board, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrabajoIndiv95</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= button_to(
        "Log in",
        new_user_session_path,
        method: :get     
         ) %>
         <br>
<%= button_to(
        "Log out",
        destroy_user_session_path,
        method: :delete
      ) %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <h3>Welcome!</h3> <%= current_user.try(:email) %>
    <%= yield %>
  </body>
</html>

app/views/publications/_form.html.erb
<%= form_with(model: publication) do |form| %>
  <% if publication.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
        <% publication.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_field :content %>
  </div>

  <div>
    <%= form.label :tag_id, style: "display: block" %>
    <%= form.collection_select:tag_id, @tag, :id, :name %>
    <%#= form.text_field :tag_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>
<br>
  <div>
    <%= form.label :foto %>
    <%= form.file_field :foto%>
  </div>
<br>
  <div>
    <%= form.submit "Crear" %>
  </div>
<% end %>

app/views/publications/_publication.html.erb
<div id="<%= dom_id publication %>">
  <p>
    <strong>Title:</strong>
    <%= publication.name %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= publication.content %>
  </p>

  <p>
    <strong>Tag:</strong>
    <%= publication.tag_id %>
    <%# <% @tags.each do |t| %>
    <%#= t.name if publication.tag_id == t.id %> 
  </p>

  <p>
    <strong>User:</strong>
    <%= publication.user_id %>
  </p>

<% if publication.foto.attached? %>
  <%= image_tag publication.foto, class: "foto-publication" %>
  <% end %>
</div>

app/views/publications/edit.html.erb
<h1>Editing publication</h1>

<%= render "form", publication: @publication %>

<br>

<div>
  <%= link_to "Show this publication", @publication %> |
  <%= link_to "Back to publications", publications_path %>
</div>

app/views/publications/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Publications</h1>

<div id="publications">
  <% @publications.each do |publication| %>
    <%= render publication %>
    <p>
      <%= link_to "Show this publication", publication %>
    </p>
  <% end %>
</div>

<% if user_signed_in? %>
  <%= link_to "New publication", new_publication_path %>
<% end %>

app/views/publications/new.html.erb
<h1>New publication</h1>

<%= render "form", publication: @publication %>

<br>

<div>
  <%= link_to "Back to publications", publications_path %>
</div>

app/views/publications/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @publication %>

<div>
  <%= link_to "Edit this publication", edit_publication_path(@publication) %> |
  <%= link_to "Back to publications", publications_path %>

  <%= button_to "Destroy this publication", @publication, method: :delete %>
</div>

app/views/tags/_form.html.erb
<%= form_with(model: tag) do |form| %>
  <% if tag.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
        <% tag.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/_tag.html.erb
<div id="<%= dom_id tag %>">
  <p>
    <strong>Name:</strong>
    <%= tag.name %>
  </p>

</div>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render "form", tag: @tag %>

<br>

<div>
  <%= link_to "Show this tag", @tag %> |
  <%= link_to "Back to tags", tags_path %>
</div>

app/views/tags/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tags</h1>

<div id="tags">
  <% @tags.each do |tag| %>
    <%= render tag %>
    <p>
      <%= link_to "Show this tag", tag %>
    </p>
  <% end %>
</div>

<%= link_to "New tag", new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render "form", tag: @tag %>

<br>

<div>
  <%= link_to "Back to tags", tags_path %>
</div>

app/views/tags/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tag %>

<div>
  <%= link_to "Edit this tag", edit_tag_path(@tag) %> |
  <%= link_to "Back to tags", tags_path %>

  <%= button_to "Destroy this tag", @tag, method: :delete %>
</div>